name: Frontier Package to NPM
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version to be released to NPM'
        required: true
      isBeta:
        description: 'Is a Beta release'
        required: true
        default: false
        type: boolean
      createTag:
        description: 'Should a new tag be created'
        required: true
        default: true
        type: boolean
  push:
    branches:
      - main
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - name: Publish to NPM
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci # Clean install
      - run: "npm publish --non-interactive ${{ $IS_BETA && '--tag beta' || '' }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          IS_BETA: ${{ inputs.isBeta }}
