name: Frontier Package to NPM
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version to be released to NPM'
        required: true
      isBeta:
        description: 'Is a Beta release'
        required: true
        default: false
        type: boolean
      createTag:
        description: 'Should a new tag be created'
        required: true
        default: true
        type: boolean
  push:
    branches:
      - main
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Publish if the version has been updated
        uses: pascalgn/npm-publish-action@1.3.9
        with: # All of theses inputs are optional
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: "${{ inputs.createTag }}"
          commit_pattern: "^Release (\\S+)"
          workspace: "."
          publish_command: "npm"
          publish_args: "${{ inputs.isBeta && '--tag beta' || '' }} --non-interactive"
        env: # More info about the environment variables in the README
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings
